Add support for AI21 models
dust-tt/dust pull request #116
Opened 2022-12-21 13:45 UTC by alexisrobert

Hello :)

I added support for AI21.com LLM models in a new provider. This is my first contribution for Dust, so I hope my patch is clean :)

(I also added a small edit for the Cohere provider where there's a small typo where the return provider arg was OpenAI instead of Cohere)

2022-12-21 14:01 UTC, spolu reviewed
Looks great. Need to test it and left a small question.

Also no support for token streaming?

2022-12-21 15:10 UTC, alexisrobert commented on core/src/providers/ai21.rs
> +                stop,
You mean topKReturn ? If so, indeed it looks so indeed, I'll submit a new patch with support for it. But I'm not 100% sure the parameters are iso.

2022-12-21 15:11 UTC, alexisrobert commented
Thanks :) I haven't seen support for token streaming in the documentation : https://docs.ai21.com/reference/j1-complete — but I might be wrong.

(I've based myself on the Cohere provider code, as their APIs seemed pretty near from each other)

2023-01-03 11:40 UTC, spolu requested changes

2023-01-03 11:40 UTC, spolu commented on front/pages/api/providers/[pId]/check.js
> +              body: JSON.stringify({ text: "Hello World" }),
Let's add a max tokens = 1

2023-01-03 11:40 UTC, spolu commented on front/components/providers/AI21Setup.jsx
> +                      Setup AI21 Studio
Should we remove the "Studio" and just say "AI21" here and in the provider name?

2023-01-03 11:42 UTC, spolu commented
Note there is no streaming support here, but I haven't been able to find it available for AI21

2023-01-03 11:43 UTC, spolu commented on front/components/providers/AI21Setup.jsx
> +                      Setup AI21 Studio
As per IRL: let's keep it

2023-01-03 11:47 UTC, romainhuet commented
Thank you for this pull request, @alexisrobert!

I wanted to check it out to test AI21 Studio models, and used this opportunity to add the corresponding frontend integration: I added AI21 to the list of model providers with the component to set the API key, and it’s now possible to select `j1-*` models from an `llm` block in the interface when building an app. I also did a tiny Rust refactor and fixed the empty `top_logprobs` to return `None`.

Let me know if you have any thoughts!

2023-01-03 11:56 UTC, merged

2023-01-11 16:52 UTC, alexisrobert commented
Thanks @romainhuet and @spolu !! :)