Util shared function to generate model sId
dust-tt/dust pull request #1162
Opened 2023-08-28 16:50 UTC by PopDaph

We're using `sId` on our models that are 10 characters long -> this tiny PR introduces an util function to avoid having to redefine it every time. 

The function to generate the `sId` can take or not a param as we have two types of models: 
`Apps` and `Workspaces` store both a `uId` (full uuid) and the truncated 10 char `sId`, and for some other models we store only a `sId` (`ChatSessions, `EventSchema`, `ExtractedEvent`).

(Note: I did not refactored on existing migration files)

2023-08-28 20:36 UTC, fontanierh approved these changes
Lgtm thank you for this 🙏

2023-08-29 06:52 UTC, spolu requested changes
Can we remove the full Id on both models that have it (but I believe is unused)?

2023-08-29 06:54 UTC, spolu commented
Wasn't there a difference between frontend and backend generation methods? Or am I hallucinating this?

2023-08-29 07:27 UTC, PopDaph commented
> Wasn't there a difference between frontend and backend generation methods? Or am I hallucinating this?

There is also a util called `client_side_new_id`, I did not touch it, it is already returning a 10 char long substring, see here: https://github.com/dust-tt/dust/blob/d7addae5be8015264c7de2fc3ff28d5b83feb8dd/front/lib/utils.ts#L16C1-L22C2

2023-08-29 07:28 UTC, PopDaph commented
> Can we remove the full Id on both models that have it (but I believe is unused)?

I'll check and handle today in another PR  👍🏻

2023-08-29 07:59 UTC, merged