Add parents array when upserting Gdrive documents
dust-tt/dust pull request #1257
Opened 2023-09-05 12:50 UTC by lasryaric

2023-09-05 13:11 UTC, philipperolet commented
linting errors

2023-09-05 13:12 UTC, spolu commented on connectors/src/connectors/google_drive/temporal/activities.ts
> +      parents: parents.map((p) => p.id),
You want to add the file itself as well (I thiiiiiink it's not in the return of that function, is it?)

2023-09-05 13:12 UTC, philipperolet requested changes
LGTM upon confimation of the questions I asked (+ linting errors)

This makes me want to cry, this my PR for notion is awful :cry:

2023-09-05 13:12 UTC, philipperolet commented on connectors/src/connectors/google_drive/temporal/activities.ts
> +    const parents = await getFileParentsMemoized(
Does it return a parent list as per the specs of the parents field [here](https://github.com/dust-tt/dust/blob/main/core/src/data_sources/data_source.rs) line 93

2023-09-05 13:12 UTC, philipperolet commented on connectors/src/connectors/google_drive/temporal/activities.ts
> +      parents: parents.map((p) => p.id),
importantly the first element of the array must be the document id itself; is it the case here?

2023-09-06 12:32 UTC, philipperolet approved these changes
LGTM :+1:

2023-09-06 13:14 UTC, merged