UserMessage component basics
dust-tt/dust pull request #1418
Opened 2023-09-12 16:30 UTC by PopDaph

Very basic first iteration, just so that it can be reused for the AgentMessage if needed. 
Next steps: 
- Handle propertly the udpate on the layout so that we can have the grey background on the full width.
- Handle markdown. 
- Handle mentions (pending some API work first)

<img width="1797" alt="Capture d’écran 2023-09-12 à 18 26 37" src="https://github.com/dust-tt/dust/assets/3803406/3a9d0dda-d5dc-48bf-a8d0-dfacee2929d5">

2023-09-12 16:37 UTC, spolu commented on front/components/assistant/conversation/Conversation.tsx
> +function UserMessage({ message }: { message: UserMessageType }) {
Let’s make it a separate component right away?

2023-09-12 16:55 UTC, philipperolet requested changes
+1 on making a separate component right away, otherwise lgtm :relaxed: 

Also, question on a container component Message (in which UserMessages and AgentMessages would be) since there is common stuff to be done exactly the same way (avatars, top button positions etc) and preventing divergence would help
But maybe too soon?

2023-09-12 18:41 UTC, spolu requested changes

2023-09-12 18:42 UTC, spolu commented
Looks great! Left a small change request on who manages the width, I think it should be the Conversation component not the message one.

2023-09-13 07:33 UTC, PopDaph commented on front/components/assistant/conversation/UserMessage.tsx
> +      <div className="mx-auto flex max-w-4xl gap-4 px-6">
agreed, I added a commit: https://github.com/dust-tt/dust/pull/1418/commits/31bb8354dfda81295090bd130849369a8d7891fd
Good for you?

2023-09-13 08:48 UTC, spolu approved these changes

2023-09-13 08:54 UTC, merged