Copy review
dust-tt/dust pull request #1718
Opened 2023-09-22 17:35 UTC by Duncid

2023-09-22 17:44 UTC, spolu approved these changes, later dismissed

2023-09-23 17:44 UTC, Duncid commented
- @PopDaph Modifying quite heavily Help content
- @fontanierh editing the copy of Assistant

2023-09-23 19:45 UTC, Duncid commented
@gabhubert It's a good place to comment & propose changes to the copy.
You can test here:
https://front-edge.dust.tt/w/0ec9852c2f/assistant/new

2023-09-23 19:46 UTC, Duncid commented
@PopDaph would be really cool to make the Assistants in the Assistant Gallery clickable (it would insert the @mention in the field).

2023-09-25 07:26 UTC, spolu requested changes
Looks great. Left 2 comments that need addresing :+1:

2023-09-25 07:26 UTC, spolu commented on front/pages/w/[wId]/assistant/new.tsx
> +        <div className="s-text-sm s-font-normal s-text-element-800">
`s-` classes are not supported in `front` so I guess you can just remove that div?

2023-09-25 07:26 UTC, spolu commented on front/pages/w/[wId]/assistant/new.tsx
> +interface Agent {
This is a bit heavy to define an interface for such a simple component. Let's just have

```
const AvatarListItem = function({ agent } : { agent : { ... }}) { ... } 
```

2023-09-25 08:35 UTC, merged