[Ahuna] Duplicate assistant
dust-tt/dust pull request #2917
Opened 2023-12-18 14:51 UTC by lasryaric

Framing for duplicating an assistant actually requires to land on the assistant creation UI with the state pre-filled, so here is the PR.
The [task](https://github.com/dust-tt/dust/issues/2651) as initially framed on `go/v2` missed that from the framing, it was a bit hard to spot.

2023-12-18 16:33 UTC, spolu requested changes
Sharing should not be conditioned on agentConfigurationId
We should use /new for duplicate not the URL of the editor of the pre-existing agentConfiguration. This is quite disatisfying + quite a foot gun as a future developer might decide to act on the URL agentConfigurationId in unexpected ways

Pre-filling new which is equally easy is much cleaner IMHO

2023-12-18 16:33 UTC, spolu commented on front/components/assistant_builder/AssistantBuilder.tsx
> +          {agentConfigurationId && (
why remove it? We want to have TeamSharing on agent creation?

2023-12-18 16:33 UTC, spolu commented on front/components/assistant_builder/AssistantBuilder.tsx
> +          {agentConfigurationId && (
You should allow agentConfigurationId = null as we def want team sharing to be visible for new agents

2023-12-18 16:33 UTC, spolu commented on front/components/assistant_builder/TeamSharingSection.tsx
>                  onClick={() => setShowCreateDuplicateDialog(true)}
this is unexpected as you show a dialog and you are wrapped in a Link at the same time?

2023-12-18 16:33 UTC, spolu commented on front/components/assistant_builder/TeamSharingSection.tsx
> +              href={`/w/${owner.sId}/builder/assistants/${agentConfigurationId}?flow=personal_assistants&copy=true`}
This is quite disatisfying that the URL preserve the old agentConfigurationId

Let's instead use `assitsants/new?duplicate={agentConfigurationId}`

2023-12-18 16:33 UTC, spolu commented on front/components/assistant_builder/TeamSharingSection.tsx
> +              href={`/w/${owner.sId}/builder/assistants/${agentConfigurationId}?flow=personal_assistants&copy=true`}
I worry it will lead to bad bugs in the future. Pre-filling a `new` page looks much safe

2023-12-18 16:44 UTC, lasryaric commented
Our IRL conversation on our way to get lunch made me think that you were recommending the solution presented in this PR.

I will work on a solution using new as I agree it is cleaner, but this won't be "one line of code".

2023-12-19 15:15 UTC, lasryaric commented
Closing in favor of: https://github.com/dust-tt/dust/pull/2945

2023-12-19 15:15 UTC, closed without merging