Fix Slack full sync await on childs
dust-tt/dust pull request #3335
Opened 2024-01-19 15:07 UTC by lasryaric

## Description

The Slack fullsync workflow was not properly waiting on child workflows added after the first batch (via signals).

This PR fixes that issue.

I was able to reproduce the bug locally:
- Add Slack channels A and B
- Add Slack channels C and D
- The child workflows C and D shows as "terminated by parents policy" once the workflows for channels A and B are completed.

## Risk

## Deploy Plan

2024-01-19 15:08 UTC, flvndvd requested changes

2024-01-19 15:08 UTC, flvndvd commented on connectors/src/connectors/slack/temporal/workflows.ts
>    await fetchUsers(connectorId);
Let's remove `promises` then.

2024-01-19 15:13 UTC, flvndvd approved these changes

2024-01-19 15:14 UTC, merged

2024-01-22 08:18 UTC, flvndvd commented
> @flvndvd @lasryaric What caused the promises to not be awaited? I believe this pattern has been used in other places of the code base no? Does it need fixing there as well?

The issue resolved here concerns how Temporal manages workflows. Due to the design where each channel ID initiates a new child workflow, using Promise.all() did wait for all the promises queued in p-queue but somehow not the one queued in the signal handler, resulting in incomplete execution of child workflows. Temporal's default policy terminates any child workflows once the parent completes.

We should even refactor this one step further to make it not async and move to a similar pattern used in Confluence implementation (see https://github.com/dust-tt/dust/pull/3326).

2024-01-22 17:46 UTC, lasryaric commented
Another way to see it:
- we get the channel ids via a signal when the workflow starts for the
first time.
- we pqueue them and await on the promises of the first signal
- on subsequent signals, we enqueue them but never wait on them, so the
child workflow get killed because the main workflow terminates.

With await queue.onIdle(), it’s all great, we wait until all pqueued
elements are done processing.

I checked all other instances of the code and the usage of pqueue seemed
correct.

On Mon, Jan 22, 2024 at 9:18 AM Flavien David ***@***.***>
wrote:

> @flvndvd <https://github.com/flvndvd> @lasryaric
> <https://github.com/lasryaric> What caused the promises to not be
> awaited? I believe this pattern has been used in other places of the code
> base no? Does it need fixing there as well?
>
> The issue resolved here concerns how Temporal manages workflows. Due to
> the design where each channel ID initiates a new child workflow, using
> Promise.all() did wait for all the promises queued in p-queue but somehow
> not the one queued in the signal handler, resulting in incomplete execution
> of child workflows. Temporal's default policy terminates any child
> workflows once the parent completes.
>
> We should even refactor this one step further to make it not async and
> move to a similar pattern used in Confluence implementation (see #3326
> <https://github.com/dust-tt/dust/pull/3326>).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dust-tt/dust/pull/3335#issuecomment-1903467221>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACXUNM7XSCJN4CSPCML2XLYPYOFNAVCNFSM6AAAAABCCC5XYOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBTGQ3DOMRSGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>