Added a warning for when the user has edited a dataset and attempts to navigate away without saving
dust-tt/dust pull request #35
Opened 2022-10-24 14:44 UTC by aickin

I handled both browser-level `onbeforeunload` events and next.js router events where the browser doesn't think the page has reloaded but the URL changes. The edit dataset page should now give a warning if you edit the description or data without hitting "Update" and you try to navigate away, either by clicking an in-app link or by typing in a new address to the browser bar. It will not pop up the warning if you click "Update".

(Note that I added an existing npm package `react-beforeunload`. I did a cursory read of the code in github, and it seems small and correct, and it's offered under MIT. I did not do any kind of security audit to make sure that the npm module has the same code as the github repo.)

2022-10-24 16:15 UTC, spolu requested changes
Extremely minor cosmetic change, otherwise looks great and successfully tested it locally :+1:

2022-10-24 16:15 UTC, spolu commented on front/pages/[user]/a/[sId]/datasets/[name]/index.jsx
> +  // this is a little wonky, but in order to redirect to the datasets main page and not
We try to have comments presented as full sentence: aka capitalized at the beginning and finished with a dot (already the case)

2022-10-24 16:15 UTC, spolu commented on front/pages/[user]/a/[sId]/datasets/[name]/index.jsx
> +  // add handlers for browser navigation (typing in address bar, refresh, back button)
same here

2022-10-24 16:15 UTC, spolu commented on front/pages/[user]/a/[sId]/datasets/[name]/index.jsx
> +      // most browsers no longer support custom messages, but for those
same

2022-10-24 16:15 UTC, spolu commented on front/pages/[user]/a/[sId]/datasets/[name]/index.jsx
> +  // add handler for next.js router events that don't load a new page in the browser.
same

2022-10-24 16:17 UTC, spolu commented
Note for self: MAKE SURE TO RUN `npm install` during deploy

2022-10-25 07:20 UTC, aickin commented
Thanks for the review; I fixed the comment formatting in in 08c8819.

2022-10-25 07:27 UTC, spolu approved these changes
LGTM

2022-10-25 07:59 UTC, merged