WIP deployments on kube
dust-tt/dust pull request #427
Opened 2023-05-11 14:57 UTC by fontanierh

2023-05-22 15:57 UTC, fontanierh commented on front/Dockerfile
> +FROM node:18.15.0-alpine as front
it's a very bare-bone Dockerfiles, there might be some ways to improve build speed (I'm not yet a Docker expert)

2023-05-22 16:05 UTC, fontanierh commented on .github/workflows/deploy-front-edge.yml
> +      - name: Setup kubectl
note: if I am not mistaken, `kubectl` is already pre-installed on GH's `ubuntu-latest`

2023-05-22 16:07 UTC, fontanierh commented on .github/workflows/deploy-front-edge.yml
> +      - name: Build the image on Cloud Build
We technically dont _have_ to use cloud build. I already implemented it like this for local use, so I kept it as-is, but it seems a bit slow so I might change it to build directly inside the action

2023-05-23 08:25 UTC, spolu commented on k8s/configmaps/front-configmap.yaml
> +  DD_SERVICE: "front-edge"
should this be `front-edge-configmap.yaml` in prevision of having both `front` and `front-edge` ?

2023-05-23 08:36 UTC, spolu requested changes
Looks great! 

Let's rename all resources that will need to be duplicated for `front` into `front-edge`. Update scripts, PR description and runbooks accordingly :+1:

2023-05-23 08:57 UTC, fontanierh commented
@spolu  PR and OP updated. Updating runbook now 👍

2023-05-23 09:07 UTC, spolu requested changes
Last `nit` 

move `cloud-build.sh` `cloudbuild.yaml` `deploy-edge.sh` `env-to-secret.sh` to `front/admin` ?

2023-05-23 09:07 UTC, spolu requested changes
Last `nit` 

move `cloud-build.sh` `cloudbuild.yaml` `deploy-edge.sh` `env-to-secret.sh` to `front/admin` ?

2023-05-23 09:50 UTC, fontanierh commented
moved @spolu

2023-05-23 09:50 UTC, spolu approved these changes
:shipit:

2023-05-23 09:51 UTC, merged