Feat: new workspace Invite Email flow
dust-tt/dust pull request #464
Opened 2023-05-23 10:14 UTC by spolu

Re-instated Invite by Email PR (cc @popdaph)

2023-05-23 10:14 UTC, spolu commented
(rebased on main, will iterate on it)

2023-05-24 14:07 UTC, spolu commented
![Screenshot from 2023-05-24 16-07-12](https://github.com/dust-tt/dust/assets/15067/5d0d049f-ce80-45b4-8652-c2faccf6e410)
![Screenshot from 2023-05-24 16-06-54](https://github.com/dust-tt/dust/assets/15067/ed0658ee-fba8-46d3-84d0-7156dd7f2da7)
![Screenshot from 2023-05-24 16-06-44](https://github.com/dust-tt/dust/assets/15067/2b6ab414-eb29-48a4-9919-da7e6ac9672d)

2023-05-24 15:35 UTC, lasryaric requested changes

2023-05-24 15:35 UTC, lasryaric commented on front/pages/api/login.ts
> +          await m.save();
And to be honest I don't understand the logic here. If the membership is revoked then the user becomes a user instead of something else?

2023-05-24 15:35 UTC, lasryaric commented on front/pages/api/login.ts
> +      // does not already exist and mark the invitation as consumed.
```suggestion
      // it does not already exist and mark the invitation as consumed.
```

2023-05-24 15:36 UTC, lasryaric commented
Looks good overall except the `revoked` role in `Membership`.

2023-05-24 15:45 UTC, lasryaric approved these changes

2023-05-24 15:46 UTC, merged