[GoogleDrive] Add full sync workflow
dust-tt/dust pull request #532
Opened 2023-06-02 14:00 UTC by lasryaric

2023-06-05 13:22 UTC, spolu approved these changes
Left a few questions to make sure I understand everything but otherwise LGTM

If I understand correctly:
- full sync:
  - loop on all files, for each get all parents and decide to sync or not, finally sync
- incremental sync:
  - same but relying on gdrive "updates"
  
I'm a bit worried by the "get all parents for each file" should we memoize it right now? We should probably memoize the intermediary steps aka the parents for a given directory? We probably want a TTL on that as directories can easily move around?

2023-06-05 13:22 UTC, spolu commented
Ah yeah as part of the questions there are a few remarks on the text formatting that I think are worth addressing.

2023-06-05 13:25 UTC, spolu requested changes
Left a few requests on what we capture at the document level

2023-06-05 13:25 UTC, spolu commented on connectors/src/connectors/google_drive/temporal/activities.ts
> +    fileId,
Let's maybe prepend "gdrive-" here?

2023-06-05 13:25 UTC, spolu commented on connectors/src/connectors/google_drive/temporal/activities.ts
> +  const tags = [`title:${res.data.title}`];
Eg lastUpdated ?

2023-06-12 11:00 UTC, lasryaric reviewed
Following up on your comments @spolu. This PR is ready for review.
I am suggesting to wait for the Folders Selector PR to be ready before merging it anyway, as this one won't sync any file.

2023-06-12 12:04 UTC, spolu submitted a review, later dismissed
LGTM

Let's merge but switch `isBuilt: false` first?

2023-06-12 12:04 UTC, spolu commented on front/pages/w/[wId]/ds/index.tsx
> -    isBuilt: false,
Let's keep it as `isBuilt: false` and merge it :+1:

2023-06-12 12:24 UTC, merged