Let transcripts be processed by personal assistants
dust-tt/dust pull request #6196
Opened 2024-07-12 13:27 UTC by albandum

## Description

For now we were only able to process transcripts through Shared or Company assistants
Some users complained not understanding why they weren't receiving their transcripts.
This PR addresses the issue and lets personal assistants process the transcripts.

- This PR adds Authenticator.fromUserIdAndWorkspaceId

## Risk

## Deploy Plan

Wait for https://github.com/dust-tt/dust/pull/6222 to be merged, switch the base of this PR to main then merge.

2024-07-15 11:14 UTC, lasryaric requested changes
Add a `Authenticator::fromUserIdAndWorkspaceId()`

2024-07-15 11:14 UTC, lasryaric commented on front/temporal/labs/activities.ts
> +  const user = renderUserType(userRes);
You can use `unsafeGetUsersByModelId` from `front/lib/api/user.ts`

2024-07-15 11:14 UTC, lasryaric commented on front/temporal/labs/activities.ts
> +  const agent = await AgentConfiguration.findOne({
use `getAgentConfiguration()` from `front/lib/api/assistant/configuration.ts`

2024-07-15 11:49 UTC, lasryaric commented on front/lib/auth.ts
> +   * Get an Authenticator for the target workspace associated with the specified user.
Add a comment saying "to be used only in context where you can't get an authenticator object from a secured key (session or API Key).

2024-07-18 13:55 UTC, albandum commented
Replaced by https://github.com/dust-tt/dust/pull/6323 after conflicts resolution of UserResource

2024-07-18 13:55 UTC, closed without merging