auto mode for chat timerange picker
dust-tt/dust pull request #675
Opened 2023-06-26 07:38 UTC by philipperolet

Draft PR for sharing / experimentation
Current issues whose path to improvement are unclear:
- Falls back on "all time" often. Fine, but the user sees it in the query loading so a bit dissapointing
- might encourage users to ask "what did I say about XX 3 weeks ago?" --- which is not handled at present and cannot be handled simply on a UX perspective
- Examples of okayish behaviour
  - "company roadmap Q1 2023?" => "all"
- Examples of wrong behaviour
  - "In january, was there a meeting in which we discussed the hiring targets?" => "month" (question asked with date 31 may)
  - "Describe the incident in production that happened 3 weeks ago" => "3 weeks" (invalid value)
  - "What was the revenue target for last year?" => "year" ( asked with date 31/05; the targets were probably set Q1 last year or even Q4 of the preceding year so they will likely be missed)

2023-06-26 07:50 UTC, philipperolet commented
![image](https://github.com/dust-tt/dust/assets/5437393/e47aba53-3195-409b-87d8-d0cd9a057891)

2023-06-26 07:51 UTC, philipperolet commented
![image](https://github.com/dust-tt/dust/assets/5437393/0c80d5e3-48ab-40a0-9c28-2944ad11d0d3)

2023-06-26 08:12 UTC, spolu requested changes
Looks great! Left one comment that needs addressing.

Otherwise, I suggest we move to a more flexible time picker when generated (fine if the user can't set 3 weeks but if the model can I think as a first step)

See: https://github.com/dust-tt/dust/blob/main/front/components/use/GensTimeRangePicker.tsx

Won't be the same as we need the `auto` and stuff but I think the timeRange model + associated functions call here: https://dust.tt/w/78bda07b39/a/699bfebc61 might be more expressive.

Can be tackled in a subsequent PR if you prefer :+1:

2023-06-26 08:12 UTC, spolu commented on front/types/chat.ts
> +import { TimeRangeId } from "@app/components/use/ChatTimeRangePicker";
Nope :)

Def not want to have types imported from a component in here. The idea of these types is to be our source of truth for types that go through the network interface.

Def want to move the TimeRangeId here instaed of the other way around

2023-06-26 13:41 UTC, philipperolet commented
> Looks great! Left one comment that needs addressing.
> 
> Otherwise, I suggest we move to a more flexible time picker when generated (fine if the user can't set 3 weeks but if the model can I think as a first step)
> 
> See: https://github.com/dust-tt/dust/blob/main/front/components/use/GensTimeRangePicker.tsx
> 
> Won't be the same as we need the `auto` and stuff but I think the timeRange model + associated functions call here: https://dust.tt/w/78bda07b39/a/699bfebc61 might be more expressive.
> 
> Can be tackled in a subsequent PR if you prefer +1

Yes agree flexibility can be tried and may solve a few issues mentioned above; that being said, would recommend not pushing to production until we have an eval

2023-06-26 13:48 UTC, spolu commented
Right now the model just choose 1 week 1 month 1 year right?

2023-06-26 20:38 UTC, philipperolet commented
Yes, or all time

2023-06-27 07:21 UTC, spolu commented
Roger that. Awaiting update for another pass of review :+1:

2023-07-17 17:01 UTC, closed without merging