Feat/remove channel permissions slack
dust-tt/dust pull request #981
Opened 2023-07-26 13:21 UTC by fontanierh

2023-07-26 19:14 UTC, spolu reviewed
Looks great!

2023-07-27 11:40 UTC, spolu requested changes
Looks great! Small visual nits

- Let's hide the checkbox to include new channel while it's not ready
- The button should be items-center aligned with the titles
- The reauthorized button can be a bit lower and aligned left with the title

2023-07-27 11:41 UTC, spolu commented
The plan is to have generic parameter in the updatePermission route for that checkbox right?

2023-07-27 12:09 UTC, fontanierh commented
> The plan is to have generic parameter in the updatePermission route for that checkbox right?

Either in the `updatePermission` or the `updateConnector` routes. I was slightly leaning towards the latter

2023-07-27 12:37 UTC, fontanierh commented
<img width="676" alt="Screenshot 2023-07-27 at 14 36 37" src="https://github.com/dust-tt/dust/assets/14199823/2f52e528-ba64-40f9-8d34-1a33906905ed">
<img width="674" alt="Screenshot 2023-07-27 at 14 36 28" src="https://github.com/dust-tt/dust/assets/14199823/5af19b67-699d-4ee5-a1c3-6532d5804cf2">

@spolu:
- removed the `include new channel` checkbox
- aligned the close/save/cancel buttons with the main title
- lowered the "re-auth" button a bit (I don't think I can left align more than this ?)

2023-07-27 13:14 UTC, spolu approved these changes
LGTM 

Thanks thanks!

2023-07-27 13:21 UTC, merged